name: 'Clean tag action'
description: 'Clean tag action to be used in build and push image to Registry'
inputs:
  tag:
    description: 'A value to be transformed into tag'
    required: true
outputs:
  tag:
    description: 'The transformed tag'
    value: ${{ steps.clean_tag_generator.outputs.clean_tag }}

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Clean tag
      id: clean_tag_generator
      run: echo "clean_tag=$(clean_tag_generator.rb ${{ inputs.tag }})" >> $GITHUB_OUTPUT
      shell: bash
